{% set name = "changeseqbe" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - biopython
    - bwa=0.7.17
    - htseq
    - matplotlib
    - numpy
    - pandas
    - pyfaidx
    - pygments
    - pysam
    - cutadapt=3.4
    - pyyaml=5.4.1
    - regex
    - scipy
    - setuptools
    - sqlite
    - statsmodels
    - svgwrite
    - yaml
    - zlib
    - htslib=1.9
    - samtools=1.9
    - bedtools

about:
  home: https://github.com/tsailabSJ/changeseq/tree/dev
  summary: "CHANGE-seq-BE"
extra:
  recipe-maintainers:
    - YichaoOU
